services:
  web:
    build:
      context: ./apache-php
    container_name: lamp-apache-php
    ports:
      - "80:80"
    volumes:
      - ./apache-php/config/php.ini:/usr/local/etc/php/php.ini
      - ./apache-php/config/custom.conf:/etc/apache2/conf-enabled/custom.conf
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - lamp-net

  db:
    image: mariadb:11
    container_name: lamp-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lamp-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 50M
    depends_on:
      - db
    networks:
      - lamp-net

volumes:
  db_data:

networks:
  lamp-net:
